#!/usr/bin/with-contenv bash
# shellcheck shell=bash

for cron_user in root; do
    if [[ -f "/etc/crontabs/${cron_user}" ]]; then
        lsiown "${cron_user}":"${cron_user}" "/etc/crontabs/${cron_user}"
        crontab -u "${cron_user}" "/etc/crontabs/${cron_user}"
    fi
done
